---
- name: provision servers
  hosts: localhost
  connection: local
  vars_files:
    - "vars/{{ env }}.yml"
  roles:
    - create_server

- name: install python2
  hosts: galera_servers
  user: ubuntu
  become: true
  become_user: root
  gather_facts: false
  vars_files:
    - "vars/{{ env }}.yml"
  roles:
    - python2

- name: install galera
  hosts: galera_servers
  user: ubuntu
  become: true
  become_user: root
  vars_files:
    - "vars/{{ env }}.yml"
  roles:
    - install_galera

- name: bootstrap galera
  hosts: galera_servers[0]
  user: ubuntu
  become: true
  become_user: root
  vars_files:
    - "vars/{{ env }}.yml"
  roles:
    - bootstrap_galera

- name: start galera
  hosts: galera_servers
  user: ubuntu
  become: true
  become_user: root
  vars_files:
    - "vars/{{ env }}.yml"
  roles:
    - start_galera
