---
- name: add galera repository key
  apt_key:
    id: BC19DDBA
    keyserver: keyserver.ubuntu.com

- name: add apt repository for mysql wsrep
  apt_repository:
    repo: deb http://releases.galeracluster.com/mysql-wsrep-5.7/ubuntu xenial main

- name: add apt repository for galera
  apt_repository:
    repo: deb http://releases.galeracluster.com/galera-3/ubuntu xenial main

- name: install galera binaries
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - galera-3
    - galera-arbitrator-3
    - mysql-wsrep-5.7
  register: install_binaries

- name: configure mysql
  template:
    src: my.cnf.j2
    dest: /etc/mysql/mysql.conf.d/mysqld.cnf
